### ISSUE TITLE
Checking release date

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/ReleaseTools#62] opened 2019-12-09 14:03 UTC
Suggestion by @lhsoicher: why not to check release date in PackageInfo.g while running ReleaseTools? 

Leonard suggests that one should be able to override it (I can envisage situations when that happens, e.g. when one publishes a release for someone else), but by default it could stop with an error message telling that the release date in PackageInfo.g is different from today's date.

**Comment by fingolfin** [comment] 2019-12-09 14:04
Duplicate of issue #21. Patches welcome :-)

**Closed by fingolfin** 2019-12-09 14:04 UTC
